### ISSUE TITLE
Soundcloud Icon

### ISSUE THREAD

**Issue by sarahlshowers** [FrontEndHappyHour/website#9]
URL for the soundcloud icon in banner sends user to a page of markdown at this url http://feeds.soundcloud.com/users/soundcloud:users:206137365/sounds.rss
![screen shot 2016-03-16 at 4 43 31 pm](https://cloud.githubusercontent.com/assets/6578253/13832119/429f2e2c-eb96-11e5-8ae3-a680d12e12b6.png)

**Comment by ryanburgess** [comment]
Thanks! I'll fix that now :+1:
